name: Test electron-chrome-extensions

on:
  push:
    paths:
    - 'packages/**'
  pull_request:
    paths:
    - 'packages/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        yarn install

    - name: Build
      run: |
        yarn build

    - name: Run tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          yarn test
